### ISSUE TITLE
Feedme importing into Events element and error 

### ISSUE THREAD

**Issue by EdenOffice** [verbb/Events#123]
### Describe the bug

I'm trying to import events via FeedMe and it's throwing the error: 

**verbb\events\services\EventTypes::getEventTypeById(): Argument #1 ($id) must be of type int, string given, called in /Users/anchovy/Sites/site/vendor/verbb/events/src/variables/EventsVariable.php on line 60**

Now I can't even get into Feed Me, via the CP as it throws the 'Internal Server Error' in non-dev mode and TypeError in dev mode.

The full stack trace is:

```
2023-04-06 00:08:38 [web.ERROR] [TypeError] verbb\events\services\EventTypes::getEventTypeById(): Argument #1 ($id) must be of type int, string given, called in /site/vendor/verbb/events/src/variables/EventsVariable.php on line 60 {"trace":["#0 /site/vendor/verbb/events/src/variables/EventsVariable.php(60): verbb\\events\\services\\EventTypes->getEventTypeById()","#1 /site/vendor/twig/twig/src/Extension/CoreExtension.php(1607): verbb\\events\\variables\\EventsVariable->getEventTypeById()","#2 /site/vendor/craftcms/cms/src/helpers/Template.php(146): twig_get_attribute()","#3 /site/storage/runtime/compiled_templates/1e/1e5555e756b4f888b93ec1d64a1949bd64f16899c6f936b25539b5ff683f0835.php(38): craft\\helpers\\Template::attribute()","#4 /site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e0d83e9fa22787369fcc69f6d92655c2dbbd20f68952be8be06b52b653484279->doDisplay()","#5 /site/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()","#6 /site/storage/runtime/compiled_templates/24/24db2038e044917e5c4cdef20f14d8cce1c0b43a02c92998fbc0b6daeb21f8ab.php(227): Twig\\Template->display()","#7 /site/vendor/twig/twig/src/Template.php(171): __TwigTemplate_a8ec4a67eab3f6a1aeb38e7b93154d5d037ee084969afdfbf26bbef10279e6f9->block_content()","#8 /site/storage/runtime/compiled_templates/d1/d1c2078f100cdecc79cf75725db0ac36f2cfacd425287f8d08ae670f19ad87f8.php(592): Twig\\Template->displayBlock()","#9 /site/vendor/twig/twig/src/Template.php(171): __TwigTemplate_b29deca6a5df72cd6e48c03c47ded07a0ffce6a65dd20bfd888e6205afb4a0fd->block_main()","#10 /site/storage/runtime/compiled_templates/d1/d1c2078f100cdecc79cf75725db0ac36f2cfacd425287f8d08ae670f19ad87f8.php(376): Twig\\Template->displayBlock()","#11 /site/vendor/twig/twig/src/Template.php(171): __TwigTemplate_b29deca6a5df72cd6e48c03c47ded07a0ffce6a65dd20bfd888e6205afb4a0fd->block_body()","#12 /site/storage/runtime/compiled_templates/e9/e92d2ccb4325a231caeff7d787d6d01c0cb67c7eb2445c48e73a54891deced29.php(94): Twig\\Template->displayBlock()","#13 /site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3a45e01c6095752e8f26c37250eec4720accaf7de508f9eea2c319a8af50207a->doDisplay()","#14 /site/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()","#15 /site/storage/runtime/compiled_templates/f1/f12af50ea1ef28d8b877c1ec142f02a5d416cd373d1c1eb0587066fee45a1e53.php(56): Twig\\Template->display()","#16 /site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_460fe31e3eace320c34ba4a10068d936b50e95ad90869cb62c53137647894ee7->doDisplay()","#17 /site/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()","#18 /site/storage/runtime/compiled_templates/d1/d1c2078f100cdecc79cf75725db0ac36f2cfacd425287f8d08ae670f19ad87f8.php(179): Twig\\Template->display()","#19 /site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b29deca6a5df72cd6e48c03c47ded07a0ffce6a65dd20bfd888e6205afb4a0fd->doDisplay()","#20 /site/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()","#21 /site/storage/runtime/compiled_templates/fc/fc19d179e06aba5554f4f00b4a005d45f93578e49c563bb8bc734417265f6723.php(57): Twig\\Template->display()","#22 /site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_60f75e9729ff85528763f740fd953fbb11aa9e43faa0263a2d3ab207f68da5e5->doDisplay()","#23 /site/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()","#24 /site/storage/runtime/compiled_templates/24/24db2038e044917e5c4cdef20f14d8cce1c0b43a02c92998fbc0b6daeb21f8ab.php(69): Twig\\Template->display()","#25 /site/vendor/twig/twig/src/Template.php(394): __TwigTemplate_a8ec4a67eab3f6a1aeb38e7b93154d5d037ee084969afdfbf26bbef10279e6f9->doDisplay()","#26 /site/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling()","#27 /site/vendor/twig/twig/src/Template.php(379): Twig\\Template->display()","#28 /site/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\\Template->render()","#29 /site/vendor/twig/twig/src/Environment.php(277): Twig\\TemplateWrapper->render()","#30 /site/vendor/craftcms/cms/src/web/View.php(456): Twig\\Environment->render()","#31 /site/vendor/craftcms/cms/src/web/View.php(509): craft\\web\\View->renderTemplate()","#32 /site/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\\web\\View->renderPageTemplate()","#33 /site/vendor/yiisoft/yii2/web/Response.php(1098): craft\\web\\TemplateResponseFormatter->format()","#34 /site/vendor/craftcms/cms/src/web/Response.php(286): yii\\web\\Response->prepare()","#35 /site/vendor/yiisoft/yii2/web/Response.php(339): craft\\web\\Response->prepare()","#36 /site/vendor/yiisoft/yii2/base/Application.php(390): yii\\web\\Response->send()","#37 /site/web/index.php(12): yii\\base\\Application->run()","#38 {main}"],"memory":22975704,"exception":"[object] (TypeError(code: 0): verbb\\events\\services\\EventTypes::getEventTypeById(): Argument #1 ($id) must be of type int, string given, called in /site/vendor/verbb/events/src/variables/EventsVariable.php on line 60 at /site/vendor/verbb/events/src/services/EventTypes.php:65)"} 
```

### Steps to reproduce

1. Goto FeedMe
2. Enter a new feed setting Events as the element type.
3. Save

(this is from memory as I can't get into FeedMe anymore to reconstruct!)

### Craft CMS version

Craft Pro 4.4.6.1

### Plugin version

2.0.0-beta.9

### Multi-site?

No

**Comment by engram-design** [comment]
I can't seem to see this error on my end. Exactly what page is this being triggered from?

If you can maybe send through your `feedme_feeds` database table?

**Comment by anchovy** [comment]
Hi @engram-design - posted this issue under the wrong account doh!

Error is being triggered now when hitting the main feedme CP page: https://site/admin/feed-me/feeds

Locally I changed vendor/verbb/events/src/variables/EventsVairable.php line 60 from:
```  
return Events::$plugin->getEventTypes()->getEventTypeById($id);
```

to:
```
return Events::$plugin->getEventTypes()->getEventTypeById((int)$id);
 ```

Which allows it to work locally. 

here's the feed that's throwing the error:

```
INSERT INTO `feedme_feeds` (`id`, `name`, `feedUrl`, `feedType`, `primaryElement`, `elementType`, `elementGroup`, `siteId`, `sortOrder`, `singleton`, `duplicateHandle`, `updateSearchIndexes`, `paginationNode`, `fieldMapping`, `fieldUnique`, `passkey`, `backup`, `setEmptyValues`, `dateCreated`, `dateUpdated`, `uid`)
VALUES
	(6, 'Legacy data imports- Courses', '@storage/legacy-imports/event-imports.json', 'json', '', 'verbb\\events\\elements\\Event', '{\"craft\\\\elements\\\\Asset\":\"\",\"craft\\\\elements\\\\Category\":\"\",\"craft\\\\commerce\\\\elements\\\\Product\":\"\",\"craft\\\\elements\\\\Entry\":{\"section\":\"\",\"entryType\":\"\"},\"craft\\\\elements\\\\Tag\":\"\",\"craft\\\\elements\\\\GlobalSet\":{\"globalSet\":\"\"},\"verbb\\\\events\\\\elements\\\\Event\":\"\",\"verbb\\\\navigation\\\\elements\\\\Node\":\"\"}', NULL, 6, 0, '[\"add\",\"update\"]', 1, '', NULL, NULL, 'agxedevnrw', 1, 0, '2023-04-05 19:53:30', '2023-04-05 19:53:34', '8547aa78-63de-4ef9-ae60-b9cb81f2edd4');
```

**Comment by engram-design** [comment]
Hmm, looks like there's no event type picked for that feed (or its been deleted), but I'll get that fixed shortly.
