### ISSUE TITLE
Upgrade to Events 3.0.0-beta.4 Failed 

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/Events#153]
### Describe the bug

Wanted to give the new Events beta a try, but a migration is failing. 

Tried upgrading everything from a stable Craft 4 build to 5, the events3 migration is having issues.

```
Exception: Setting unknown property: verbb\events\records\TicketType::minQty (/var/www/html/vendor/yiisoft/yii2/base/Component.php:217)
#0 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(322): yii\base\Component->__set('minQty', NULL)
#1 /var/www/html/vendor/craftcms/cms/src/db/ActiveRecord.php(56): yii\db\BaseActiveRecord->__set('minQty', NULL)
#2 /var/www/html/vendor/verbb/events/src/elements/TicketType.php(451): craft\db\ActiveRecord->__set('minQty', NULL)
#3 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(3784): verbb\events\elements\TicketType->afterSave(true)
#4 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1221): craft\services\Elements->craft\services\{closure}()
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(3589): craft\services\Elements->ensureBulkOp(Object(Closure))
#6 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1307): craft\services\Elements->_saveElementInternal(Object(verbb\events\elements\TicketType), true, false, NULL, Array, false, false, false)
#7 /var/www/html/vendor/verbb/events/src/migrations/m240921_000000_events3.php(438): craft\services\Elements->saveElement(Object(verbb\events\elements\TicketType))
#8 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): verbb\events\migrations\m240921_000000_events3->safeUp()
#9 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#10 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(382): yii\console\controllers\BaseMigrateController->migrateUp('m240921_000000_...')
#11 [internal function]: craft\console\controllers\MigrateController->actionAll()
#12 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(195): yii\console\Controller->runAction('all', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#17 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#18 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#19 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#20 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#22 /var/www/html/craft(13): yii\base\Application->run()
#23 {main}
*** failed to apply m240921_000000_events3 (time: 3.919s)
```

### Steps to reproduce

1. Upgrade everything to latest stable Craft 4 versions
2. Do upgrade to Craft 5

### Craft CMS version

5.4.7.1

### Plugin version

3.0.0-beta4

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.5](https://github.com/verbb/events/releases/tag/3.0.0-beta.5), and keen to get your thoughts on the new features and workflow!
